Learning Numpy :-

In [1]:
import numpy as np

In [2]:
lst= [1,2,3,4,5,6,7,8,9,10]
%timeit [i**2 for i in lst]

6.45 µs ± 1.01 µs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [3]:
arr= np.array(lst)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
lst+ [1]


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1]

In [5]:
arr+ [1]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Please Note: Numpy arrays are homogeneous,only one type of variable in one array
Different ways to create np array:-

(i) np.array() 
(ii) np.arange()

In [6]:
np_arr = np.array(lst)
np_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
np_arr.ndim


1

In [8]:
np_arr.shape

(10,)

If you will do print(np_arr), It will print the np_arr like a list so in order to prevent from confusion between np_arr and simple_arr/list, we usually print np_arr as simply "np_arr"

In [9]:
new_np_arr= np.arange(3,11,2)
new_np_arr

array([3, 5, 7, 9])

In [10]:
lst_2d = [ [1,2,3],[4,5,6],[7,8,9]]
lst_2d

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np_arr_2d = np.array(lst_2d)
np_arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np_arr_2d.ndim

2

In [13]:
np_arr_2d.shape
#it gives you 'n' and 'm' of a n*m matrix.

(3, 3)

Some special arrays to create in numpy :-

In [14]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros((2,5,6))

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

In [16]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
np.diag([2,3,4,5])

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 5]])

In [18]:
np.diag(lst)

array([[ 1,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  2,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  3,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  4,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  5,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  6,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  7,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  8,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  9,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 10]])

In [19]:
np.identity(3)
#but, np.identity((3,4)) will give error

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

INDEXING IN ARRAYS:-
 
like c++ arrays : arr[i][j][k]... (also zero indexing is followed )

In [20]:
#To create random elements array or random elements
arr2=np.random.randint(0,30,(3,5))
arr2

array([[23,  4,  5,  6, 14],
       [11,  3, 18, 24,  9],
       [23, 21, 14,  7, 28]])

In [21]:
#Array slicing
# new_arr= arr[start_row_idx : end_row_idx + 1, start_col_idx : end_col_idx + 1]
# you know why there is +1 in the above line
sliced_arr=arr2[1:4,2:5] 

print(arr2)
sliced_arr

[[23  4  5  6 14]
 [11  3 18 24  9]
 [23 21 14  7 28]]


array([[18, 24,  9],
       [14,  7, 28]])

In [22]:
#Another property :
sliced_arr2= arr2[1:,2:]

sliced_arr2

array([[18, 24,  9],
       [14,  7, 28]])

In [23]:
# notice the output of this snippet well :
arr2[1:,2:] = 0
arr2

array([[23,  4,  5,  6, 14],
       [11,  3,  0,  0,  0],
       [23, 21,  0,  0,  0]])

You should notice that even after entering the row index out of bound, it is not giving any error it is just showing what is possible

-> Masking :

In [24]:
masked_arr= arr2 > 10
print(arr2)
masked_arr

[[23  4  5  6 14]
 [11  3  0  0  0]
 [23 21  0  0  0]]


array([[ True, False, False, False,  True],
       [ True, False, False, False, False],
       [ True,  True, False, False, False]])

In [25]:
# if you just do the sum of all elemenst of masked_arr,
#it will give the number of elements which are greater than 10, since sum of booleans ,
# one _example
np.sum(masked_arr)

5

In [26]:
arr3 = np.array([3,4,5,6])
arr3

array([3, 4, 5, 6])

In [27]:
# dot roduct or product of matrix :
np.dot(matrix1,matrix2)


More Operation on array :-
arr4= np.arange(1,36)

print(arr4)

arr4=arr4.reshape(5,7)

#arr4 = arr4.reshape(6,4)

#arr4 = arr4.reshape(10,10)


Some other operations :-
 -> sum of all elements : np.sum(arr)
 -> min/max/mean/std deviation of array : np.min/max/mean/std(arr)
 -> 

In [ ]:
arr4 = np.arange(0,35)
# if you want the sum of elements row wise i.e. sum of 
# all elements in a row then :
np.sum(arr4,axis =0 )
np.sum(arr4,axis =1 )
np.mean(arr4, axis =0)
np.mean(arr4, axis =1)


AxisError: axis 1 is out of bounds for array of dimension 1

In [ ]:
arr4.flatten()
arr4

In [ ]:
arr4.reshape(7,5)
arr4

In [ ]:
#Tranpose of matrix 
arr4.T
arr4

In [ ]:
# Or you can also do this:
np.transpose(arr4)
arr4

Stacking of arrays :
(i) vstack  (vertical)
(ii) hstack (horizontal)

In [ ]:
np.hstack((arr5,arr6))
np.vstack((arr5,arr6))


# Broadcasting
First rule of Numpy : 2 Arrays can perform operations only if they are of same shapes.
But, still we are able to perform such tasks due to broadcasting. 

How :- A small array will repeat itself and convert to the same shape as of another array.

In [ ]:
a1 = np.random.randint(0,10,size=(3,3))
a2 = np.array([[1,2,3]])
print(a1)
print(a2)
print(a1+a2)
#print(a1+a2.T)


# Vectorization :
- performing operations directlly on arrays.

In [ ]:
# The simple code to compute euclidian distance two points point 1 and 
# point 2 where, point 1 and 2 are 1*2 matrices.
np.sqrt(np.sum((point2-point1)**2))
